name: Build & Test in Pull Request to Stage

on:
  pull_request:
    branches: [ "staging" ]

env:
  NOTI_PR_STAGING_WEBHOOK: ${{ secrets.NOTI_PR_STAGING_WEBHOOK }}

permissions:
  contents: read

jobs:
  build:
    name: Build & Test on main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ build ]
    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.check.outputs.status }}
          author_name: Build & Test before Pull Request
          job_name: Build & Test on main
          mention: 'channel'
          if_mention: 'failure, cancelled'
          fields: repo,commit,message,author,job,eventName,ref,workflow,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ env.NOTI_PR_STAGING_WEBHOOK }}
        if: always()
